### PR TITLE
Remove selenium requirement

### PR DESCRIPTION
**Pull request by evolvingpixie**
Removed the requirement for selenium and rely on the requests module instead.
Currently passing build tests https://travis-ci.org/monkeyslayer56/mychevy

---
This change is [Reviewable](https://reviewable.io/reviews/sdague/mychevy/5)

### CODE REVIEW

**Comment by sdague** [comment]
Oh man, you got it working again. Their website was so terrible up until this point that I wasn't sure this would ever work again!

:champagne: 

I'll look through the PR a little bit and try to get it merged and released soon. Thanks so much for contributing!

**Comment by sdague** [comment]
How did you figure out the new API endpoints?

**Comment by sdague** [comment]
I'm going to merge this, I have seen issues in the past where in integrating this in home assistant there can be an HTTP connection hang. Can you add a timeout of 180 seconds as a backstop to all get/post calls just in case. That can be a follow up patch.

**Comment by sdague** [comment]
Also, some README cleanup on what this actually does now would be good

**Comment by evolvingpixie** [comment]
I'll see what I can do. In my testing I've also noticed that when the mychevy site stops giving data the status code is 500 rather than 200. I may try to add some checks for that if I get the time.

**Comment by sdague** [comment]
Great, thank you. I'll see about retooling the home assistant component for this, but it's a busy week so it might be more an over christmas thing.

**Pull request merged**
